name: the_inventory
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil:
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/store/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/font/Outfit-Regular.ttf
          style: normal
    - family: Gilmer
      fonts:
        - asset: assets/font/Gilmer Regular.otf
          style: normal
    - family: Montserrat
      fonts:
        - asset: assets/font/Montserrat-Regular.ttf
          style: normal
  # fonts:
  #   - family: LibreFranklin
  #     fonts:
  #       - asset: assets/fonts/LibreFranklin-ExtraBold.ttf
  #         weight: 800
  #       - asset: assets/fonts/LibreFranklin-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/LibreFranklin-Medium.ttf
  #         weight: 600
  #       - asset: assets/fonts/LibreFranklin-Regular.ttf
  #         weight: 500
  #       - asset: assets/fonts/LibreFranklin-Light.ttf
  #         weight: 400
  #       - asset: assets/fonts/LibreFranklin-Light.ttf
